apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicea
  namespace: sample-namespace
spec:
  hosts:
    - "*"
  gateways:
    - sample-namespace/gateway
  http:
  - match:
    - headers:
        end-user:
          exact: jason
      # uri:
      #   prefix: "/"
      ignoreUriCase: true
    route:
    - destination:
        host: serviceb
  - route:
    - destination:
        host: servicec